from django.conf import settings

PRIVACYSESSIONS_AUTHED_ONLY = getattr(settings, 'PRIVACYSESSIONS_AUTHED_ONLY', False)
PRIVACYSESSIONS_REMOTE_ADDR_KEY = getattr(settings, 'PRIVACYSESSIONS_REMOTE_ADDR_KEY', 'REMOTE_ADDR')
PRIVACYSESSIONS_REDIRECT_VIEW = getattr(settings, 'PRIVACYSESSIONS_REDIRECT_VIEW', None)
PRIVACYSESSIONS_FAILURE_STATUS = getattr(settings, 'PRIVACYSESSIONS_FAILURE_STATUS', 400)
PRIVACYSESSIONS_PRIVACY_IP = getattr(settings, 'PRIVACYSESSIONS_PRIVACY_IP', True)
PRIVACYSESSIONS_IPV4_LENGTH = getattr(settings, 'PRIVACYSESSIONS_IPV4_LENGTH', 32)
PRIVACYSESSIONS_IPV6_LENGTH = getattr(settings, 'PRIVACYSESSIONS_IPV6_LENGTH', 64)
PRIVACYSESSIONS_PRIVACY_UA = getattr(settings, 'PRIVACYSESSIONS_PRIVACY_UA', True)
PRIVACYSESSIONS_IP_KEY = getattr(settings, 'PRIVACYSESSIONS_IP_KEY', '_privacysessions_ip')
PRIVACYSESSIONS_UA_KEY = getattr(settings, 'PRIVACYSESSIONS_UA_KEY', '_privacysessions_ua')
